document.getElementById('input-text').addEventListener('input', () => {
    document.getElementById('output-text').innerHTML = wrapTextInQuotes(
        document.getElementById('input-text').value
    )
})

setRandomTitle = () => {
    document.getElementById('output-text').innerHTML = wrapTextInQuotes(
        episodeTitles[getRandomInt()]
    )

    document.getElementById('input-text').placeholder =
        episodeTitles[getRandomInt()]
}

getRandomInt = () => {
    return Math.floor(Math.random() * episodeTitles.length)
}

wrapTextInQuotes = (input) => {
    return `"${input}"`
}

const episodeTitles = [
    'The Gang Gets Racist',
    'Charlie Wants an Abortion',
    'Underage Drinking: A National Concern',
    'Charlie Has Cancer',
    'Gun Fever',
    'The Gang Finds a Dead Guy',
    'Charlie Got Molested',
    'Charlie Gets Crippled',
    'The Gang Goes Jihad',
    'Dennis and Dee Go on Welfare',
    "Mac Bangs Dennis' Mom",
    'Hundred Dollar Baby',
    'The Gang Gives Back',
    'The Gang Exploits a Miracle',
    'The Gang Runs for Office',
    "Charlie Goes America All Over Everybody's Ass",
    'Dennis and Dee Get a New Dad',
    'The Gang Finds a Dumpster Baby',
    'The Gang Gets Invincible',
    "Dennis and Dee's Mom Is Dead",
    'The Gang Gets Held Hostage',
    'The Aluminum Monster vs. Fatty Magoo',
    'The Gang Solves the North Korea Situation',
    'The Gang Sells Out',
    'Frank Sets Sweet Dee on Fire',
    "Sweet Dee's Dating a Retarded Person",
    'Mac Is a Serial Killer',
    'Dennis Looks Like a Registered Sex Offender',
    'The Gang Gets Whacked (Part 1)',
    'The Gang Gets Whacked (Part 2)',
    'Bums: Making a Mess All Over the City',
    'The Gang Dances Their Asses Off',
    'Mac and Dennis: Manhunters',
    'The Gang Solves the Gas Crisis',
    "America's Next Top Paddy's Billboard Model Contest",
    "Mac's Banging the Waitress",
    'Mac and Charlie Die (Part 1)',
    'Mac and Charlie Die (Part 2)',
    'Who Pooped the Bed?',
    "Paddy's Pub: The Worst Bar in Philadelphia",
    'Dennis Reynolds: An Erotic Life',
    'Sweet Dee Has a Heart Attack',
    'The Gang Cracks the Liberty Bell',
    'The Gang Gets Extreme: Home Makeover Edition',
    'The Nightman Cometh',
    'The Gang Exploits the Mortgage Crisis',
    'The Gang Hits the Road',
    'The Great Recession',
    'The Gang Gives Frank an Intervention',
    'The Waitress Is Getting Married',
    'The World Series Defense',
    'The Gang Wrestles for the Troops',
    "Paddy's Pub: Home of the Original Kitten Mittens",
    'Mac and Dennis Break Up',
    'The D.E.N.N.I.S. System',
    'Mac and Charlie Write a Movie',
    'The Gang Reignites the Rivalry',
    'Mac Fights Gay Marriage',
    'Dennis Gets Divorced',
    'The Gang Buys a Boat',
    "Mac's Big Break",
    'Mac and Charlie: White Trash',
    "Mac's Mom Burns Her House Down",
    'Who Got Dee Pregnant?',
    'The Gang Gets a New Member',
    "Dee Reynolds: Shaping America's Youth",
    'Charlie Kelly: King of the Rats',
    'The Gang Gets Stranded in the Woods',
    'Dee Gives Birth',
    'A Very Sunny Christmas',
    "Frank's Pretty Woman",
    'The Gang Goes to the Jersey Shore',
    'Frank Reynolds’ Little Beauties',
    'Sweet Dee Gets Audited',
    "Frank's Brother",
    'The Storm of the Century',
    'Chardee MacDennis: The Game of Games',
    'The ANTI-Social Network',
    'The Gang Gets Trapped',
    'How Mac Got Fat',
    'Thunder Gun Express',
    'The High School Reunion',
    "The High School Reunion Part 2: The Gang's Revenge",
    'Pop-Pop: The Final Solution',
    'The Gang Recycles Their Trash',
    'The Maureen Ponderosa Wedding Massacre',
    'Charlie and Dee Find Love',
    'The Gang Gets Analyzed',
    "Charlie's Mom Has Cancer",
    "Frank's Back in Business",
    'Charlie Rules the World',
    'The Gang Dines Out',
    'Reynolds vs. Reynolds: The Cereal Defense',
    'The Gang Broke Dee',
    'Gun Fever Too: Still Hot',
    'The Gang Tries Desperately to Win an Award',
    'Mac and Dennis Buy a Timeshare',
    'Mac Day',
    'The Gang Saves the Day',
    'The Gang Gets Quarantined',
    'Flowers for Charlie',
    'The Gang Makes Lethal Weapon 6',
    'The Gang Squashes Their Beefs',
    'The Gang Beats Boggs',
    'The Gang Group Dates',
    'Psycho Pete Returns',
    'Charlie Work',
    'The Gang Spies Like U.S.',
    'The Gang Misses the Boat',
    'Mac Kills His Dad',
    'The Gang Goes on Family Fight',
    'Frank Retires',
    'Ass Kickers United: Mac and Charlie Join a Cult',
    'Chardee MacDennis 2: Electric Boogaloo',
    'Frank Falls Out the Window',
    'The Gang Hits the Slopes',
    'Dee Made a Smut Film',
    'Mac & Dennis Move to the Suburbs',
    'Being Frank',
    'McPoyle vs. Ponderosa: The Trial of the Century',
    'Charlie Catches a Leprechaun',
    'The Gang Goes to Hell',
    'The Gang Goes to Hell: Part Two',
    'The Gang Turns Black',
    'The Gang Goes to a Water Park',
    'Old Lady House: A Situation Comedy',
    'Wolf Cola: A Public Relations Nightmare',
    'Making Dennis Reynolds a Murderer',
    'Hero or Hate Crime?',
    'PTSDee',
    'The Gang Tends Bar',
    "A Cricket's Tale",
    "Dennis' Double Life",
    "The Gang Makes Paddy's Great Again",
    'The Gang Escapes',
    "The Gang Beats Boggs: Ladies' Reboot",
    "Time's Up for the Gang",
    'The Gang Gets New Wheels',
    'The Gang Solves the Bathroom Problem',
    'The Gang Does a Clip Show',
    "Charlie's Home Alone",
    'The Gang Wins the Big Game',
    'Mac Finds His Pride',
    'The Gang Gets Romantic',
    'Thunder Gun 4: Maximum Cool',
    'Dee Day',
    'The Gang Chokes',
    'The Gang Texts',
    'The Janitor Always Mops Twice',
    'The Gang Solves Global Warming',
    "Paddy's Has a Jumper",
    "A Woman's Right to Chop",
    'Waiting for Big Mo',
]
